name: Webhook Trigger Workflow

on:
  repository_dispatch:
    types: [run-from-webhook]

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Environment: ${{ github.event.client_payload.env }}"
          echo "Version: ${{ github.event.client_payload.version }}"
